version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "newsie"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fwiwob27z0yc"
s3_prefix = "newsie"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
